//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Accessory 的當地語系化字串。
        /// </summary>
        internal static string AccessoryMaintainString {
            get {
                return ResourceManager.GetString("AccessoryMaintainString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please input an account 的當地語系化字串。
        /// </summary>
        internal static string AccountInputString {
            get {
                return ResourceManager.GetString("AccountInputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Incorrect account or password 的當地語系化字串。
        /// </summary>
        internal static string AccountOrPasswordErrorString {
            get {
                return ResourceManager.GetString("AccountOrPasswordErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please input account and password 的當地語系化字串。
        /// </summary>
        internal static string AccountOrPasswordNullString {
            get {
                return ResourceManager.GetString("AccountOrPasswordNullString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Account 的當地語系化字串。
        /// </summary>
        internal static string AccountString {
            get {
                return ResourceManager.GetString("AccountString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please input a address 的當地語系化字串。
        /// </summary>
        internal static string AddressInputString {
            get {
                return ResourceManager.GetString("AddressInputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Address 的當地語系化字串。
        /// </summary>
        internal static string AddressString {
            get {
                return ResourceManager.GetString("AddressString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Adivosry Sn 的當地語系化字串。
        /// </summary>
        internal static string AdviosryIdString {
            get {
                return ResourceManager.GetString("AdviosryIdString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Appointment Date 的當地語系化字串。
        /// </summary>
        internal static string AppointDateString {
            get {
                return ResourceManager.GetString("AppointDateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please input area name 的當地語系化字串。
        /// </summary>
        internal static string AreaNameInputString {
            get {
                return ResourceManager.GetString("AreaNameInputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select a area 的當地語系化字串。
        /// </summary>
        internal static string AreaSelectRemindString {
            get {
                return ResourceManager.GetString("AreaSelectRemindString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Area 的當地語系化字串。
        /// </summary>
        internal static string AreaString {
            get {
                return ResourceManager.GetString("AreaString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        internal static string BridalBdayString {
            get {
                return ResourceManager.GetString("BridalBdayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        internal static string BridalCommunicationCString {
            get {
                return ResourceManager.GetString("BridalCommunicationCString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        internal static string BridalCommunicationIdString {
            get {
                return ResourceManager.GetString("BridalCommunicationIdString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bridal&apos;s Name 的當地語系化字串。
        /// </summary>
        internal static string BridalNameString {
            get {
                return ResourceManager.GetString("BridalNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bridal&apos;s Nickname 的當地語系化字串。
        /// </summary>
        internal static string BridalNicknameString {
            get {
                return ResourceManager.GetString("BridalNicknameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        internal static string BridalPassportString {
            get {
                return ResourceManager.GetString("BridalPassportString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        internal static string CancelString {
            get {
                return ResourceManager.GetString("CancelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Capacities 的當地語系化字串。
        /// </summary>
        internal static string CapacitiesString {
            get {
                return ResourceManager.GetString("CapacitiesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Case id 的當地語系化字串。
        /// </summary>
        internal static string CaseIdString {
            get {
                return ResourceManager.GetString("CaseIdString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Case Permission 的當地語系化字串。
        /// </summary>
        internal static string CasePermissionMgtString {
            get {
                return ResourceManager.GetString("CasePermissionMgtString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Church 的當地語系化字串。
        /// </summary>
        internal static string ChurchMaintainString {
            get {
                return ResourceManager.GetString("ChurchMaintainString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please input church name 的當地語系化字串。
        /// </summary>
        internal static string ChurchNameInputString {
            get {
                return ResourceManager.GetString("ChurchNameInputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Church Name 的當地語系化字串。
        /// </summary>
        internal static string ChurchNameString {
            get {
                return ResourceManager.GetString("ChurchNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select a church 的當地語系化字串。
        /// </summary>
        internal static string ChurchSelectRemindString {
            get {
                return ResourceManager.GetString("ChurchSelectRemindString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clear 的當地語系化字串。
        /// </summary>
        internal static string ClearString {
            get {
                return ResourceManager.GetString("ClearString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Simplified Chinese Name 的當地語系化字串。
        /// </summary>
        internal static string CnNameString {
            get {
                return ResourceManager.GetString("CnNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Input the code 的當地語系化字串。
        /// </summary>
        internal static string CodeInputString {
            get {
                return ResourceManager.GetString("CodeInputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Code 的當地語系化字串。
        /// </summary>
        internal static string CodeString {
            get {
                return ResourceManager.GetString("CodeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unsigned Case Maintain 的當地語系化字串。
        /// </summary>
        internal static string ConsultMaintainString {
            get {
                return ResourceManager.GetString("ConsultMaintainString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unsigned Timetable 的當地語系化字串。
        /// </summary>
        internal static string ConsultScheduleString {
            get {
                return ResourceManager.GetString("ConsultScheduleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unsigned Case 的當地語系化字串。
        /// </summary>
        internal static string ConsultString {
            get {
                return ResourceManager.GetString("ConsultString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please input the content 的當地語系化字串。
        /// </summary>
        internal static string ContentInputString {
            get {
                return ResourceManager.GetString("ContentInputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Content 的當地語系化字串。
        /// </summary>
        internal static string ContentString {
            get {
                return ResourceManager.GetString("ContentString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Contract Date 的當地語系化字串。
        /// </summary>
        internal static string ContractDateString {
            get {
                return ResourceManager.GetString("ContractDateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        internal static string ContractEndDateString {
            get {
                return ResourceManager.GetString("ContractEndDateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Contract Maintain 的當地語系化字串。
        /// </summary>
        internal static string ContractMaintainString {
            get {
                return ResourceManager.GetString("ContractMaintainString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Contract Timetable 的當地語系化字串。
        /// </summary>
        internal static string ContractScheduleString {
            get {
                return ResourceManager.GetString("ContractScheduleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Contract 的當地語系化字串。
        /// </summary>
        internal static string ContractString {
            get {
                return ResourceManager.GetString("ContractString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Input the country name 的當地語系化字串。
        /// </summary>
        internal static string CountryNameInputString {
            get {
                return ResourceManager.GetString("CountryNameInputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select a country 的當地語系化字串。
        /// </summary>
        internal static string CountrySelectRemindString {
            get {
                return ResourceManager.GetString("CountrySelectRemindString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Country 的當地語系化字串。
        /// </summary>
        internal static string CountryString {
            get {
                return ResourceManager.GetString("CountryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create 的當地語系化字串。
        /// </summary>
        internal static string CreateString {
            get {
                return ResourceManager.GetString("CreateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Input the currency name 的當地語系化字串。
        /// </summary>
        internal static string CurrencyNameInputString {
            get {
                return ResourceManager.GetString("CurrencyNameInputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Input the rate 的當地語系化字串。
        /// </summary>
        internal static string CurrencyRateInputString {
            get {
                return ResourceManager.GetString("CurrencyRateInputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rate 的當地語系化字串。
        /// </summary>
        internal static string CurrencyRateString {
            get {
                return ResourceManager.GetString("CurrencyRateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select a currency 的當地語系化字串。
        /// </summary>
        internal static string CurrencySelectionReminderString {
            get {
                return ResourceManager.GetString("CurrencySelectionReminderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Currency 的當地語系化字串。
        /// </summary>
        internal static string CurrencyString {
            get {
                return ResourceManager.GetString("CurrencyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Customer Maintain 的當地語系化字串。
        /// </summary>
        internal static string CustomerMaintainString {
            get {
                return ResourceManager.GetString("CustomerMaintainString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Customer Timetable 的當地語系化字串。
        /// </summary>
        internal static string CustomerScheduleString {
            get {
                return ResourceManager.GetString("CustomerScheduleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Customer 的當地語系化字串。
        /// </summary>
        internal static string CustomerString {
            get {
                return ResourceManager.GetString("CustomerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete 的當地語系化字串。
        /// </summary>
        internal static string DeleteString {
            get {
                return ResourceManager.GetString("DeleteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Dress 的當地語系化字串。
        /// </summary>
        internal static string DressMaintainString {
            get {
                return ResourceManager.GetString("DressMaintainString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Employee 的當地語系化字串。
        /// </summary>
        internal static string EmployeeMaintainString {
            get {
                return ResourceManager.GetString("EmployeeMaintainString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EmployeeSnString 的當地語系化字串。
        /// </summary>
        internal static string EmployeeSnString {
            get {
                return ResourceManager.GetString("EmployeeSnString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Employee 的當地語系化字串。
        /// </summary>
        internal static string EmployeeString {
            get {
                return ResourceManager.GetString("EmployeeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 English Name 的當地語系化字串。
        /// </summary>
        internal static string EnglishNameString {
            get {
                return ResourceManager.GetString("EnglishNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 English 的當地語系化字串。
        /// </summary>
        internal static string EnglishString {
            get {
                return ResourceManager.GetString("EnglishString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Export 的當地語系化字串。
        /// </summary>
        internal static string ExportString {
            get {
                return ResourceManager.GetString("ExportString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Financial Mgt 的當地語系化字串。
        /// </summary>
        internal static string FinMgtString {
            get {
                return ResourceManager.GetString("FinMgtString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Groom&apos;s Birthday 的當地語系化字串。
        /// </summary>
        internal static string GroomBdayString {
            get {
                return ResourceManager.GetString("GroomBdayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Groom&apos;s Msger 的當地語系化字串。
        /// </summary>
        internal static string GroomCommunicationCString {
            get {
                return ResourceManager.GetString("GroomCommunicationCString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Groom&apos;s Msger Id 的當地語系化字串。
        /// </summary>
        internal static string GroomCommunicationIdString {
            get {
                return ResourceManager.GetString("GroomCommunicationIdString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Groom&apos;s Name 的當地語系化字串。
        /// </summary>
        internal static string GroomNameString {
            get {
                return ResourceManager.GetString("GroomNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Groom&apos;s Nickname 的當地語系化字串。
        /// </summary>
        internal static string GroomNicknameString {
            get {
                return ResourceManager.GetString("GroomNicknameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Groom&apos;s Passport Name 的當地語系化字串。
        /// </summary>
        internal static string GroomPassportString {
            get {
                return ResourceManager.GetString("GroomPassportString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Is Valid 的當地語系化字串。
        /// </summary>
        internal static string IsValidString {
            get {
                return ResourceManager.GetString("IsValidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Package 的當地語系化字串。
        /// </summary>
        internal static string ItemPackageString {
            get {
                return ResourceManager.GetString("ItemPackageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Japanese 的當地語系化字串。
        /// </summary>
        internal static string JapaneseString {
            get {
                return ResourceManager.GetString("JapaneseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Japanese Name 的當地語系化字串。
        /// </summary>
        internal static string JpNameString {
            get {
                return ResourceManager.GetString("JpNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Language Code 的當地語系化字串。
        /// </summary>
        internal static string LangCodeString {
            get {
                return ResourceManager.GetString("LangCodeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select a language 的當地語系化字串。
        /// </summary>
        internal static string LanguageSelectionReminderString {
            get {
                return ResourceManager.GetString("LanguageSelectionReminderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Language 的當地語系化字串。
        /// </summary>
        internal static string LanguageString {
            get {
                return ResourceManager.GetString("LanguageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Last Received Time 的當地語系化字串。
        /// </summary>
        internal static string LastReceivedTimeString {
            get {
                return ResourceManager.GetString("LastReceivedTimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Location 的當地語系化字串。
        /// </summary>
        internal static string LocateString {
            get {
                return ResourceManager.GetString("LocateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Church Reservation 的當地語系化字串。
        /// </summary>
        internal static string LocationReservationString {
            get {
                return ResourceManager.GetString("LocationReservationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System Maintain 的當地語系化字串。
        /// </summary>
        internal static string LoginMaintainString {
            get {
                return ResourceManager.GetString("LoginMaintainString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select a store 的當地語系化字串。
        /// </summary>
        internal static string LoginStoreNotSelectedString {
            get {
                return ResourceManager.GetString("LoginStoreNotSelectedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Login 的當地語系化字串。
        /// </summary>
        internal static string LoginString {
            get {
                return ResourceManager.GetString("LoginString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Logout 的當地語系化字串。
        /// </summary>
        internal static string LogoutString {
            get {
                return ResourceManager.GetString("LogoutString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Main 的當地語系化字串。
        /// </summary>
        internal static string MainPageString {
            get {
                return ResourceManager.GetString("MainPageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Meal 的當地語系化字串。
        /// </summary>
        internal static string MealString {
            get {
                return ResourceManager.GetString("MealString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Member id 的當地語系化字串。
        /// </summary>
        internal static string MemberIdString {
            get {
                return ResourceManager.GetString("MemberIdString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Modified Date 的當地語系化字串。
        /// </summary>
        internal static string ModifiedTimeString {
            get {
                return ResourceManager.GetString("ModifiedTimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit 的當地語系化字串。
        /// </summary>
        internal static string ModifyString {
            get {
                return ResourceManager.GetString("ModifyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Msger Title 的當地語系化字串。
        /// </summary>
        internal static string MsgIdString {
            get {
                return ResourceManager.GetString("MsgIdString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Msger 的當地語系化字串。
        /// </summary>
        internal static string MsgString {
            get {
                return ResourceManager.GetString("MsgString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please input a name 的當地語系化字串。
        /// </summary>
        internal static string NameInputString {
            get {
                return ResourceManager.GetString("NameInputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name 的當地語系化字串。
        /// </summary>
        internal static string NameString {
            get {
                return ResourceManager.GetString("NameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Operation 的當地語系化字串。
        /// </summary>
        internal static string OperationString {
            get {
                return ResourceManager.GetString("OperationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Case Mgt 的當地語系化字串。
        /// </summary>
        internal static string OrderMgtString {
            get {
                return ResourceManager.GetString("OrderMgtString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please input password again 的當地語系化字串。
        /// </summary>
        internal static string PasswordConfirmInputString {
            get {
                return ResourceManager.GetString("PasswordConfirmInputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Password Confirmation 的當地語系化字串。
        /// </summary>
        internal static string PasswordConfirmString {
            get {
                return ResourceManager.GetString("PasswordConfirmString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please input the password 的當地語系化字串。
        /// </summary>
        internal static string PasswordInputString {
            get {
                return ResourceManager.GetString("PasswordInputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Password 的當地語系化字串。
        /// </summary>
        internal static string PasswordString {
            get {
                return ResourceManager.GetString("PasswordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Permission Category 的當地語系化字串。
        /// </summary>
        internal static string PermissionCategoryString {
            get {
                return ResourceManager.GetString("PermissionCategoryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Phone Number 的當地語系化字串。
        /// </summary>
        internal static string PhoneString {
            get {
                return ResourceManager.GetString("PhoneString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Photo 的當地語系化字串。
        /// </summary>
        internal static string PhotoString {
            get {
                return ResourceManager.GetString("PhotoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Price 的當地語系化字串。
        /// </summary>
        internal static string PriceString {
            get {
                return ResourceManager.GetString("PriceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Product 的當地語系化字串。
        /// </summary>
        internal static string ProductMaintainString {
            get {
                return ResourceManager.GetString("ProductMaintainString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Purchase Mgt 的當地語系化字串。
        /// </summary>
        internal static string PurchaseMgtString {
            get {
                return ResourceManager.GetString("PurchaseMgtString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Received 的當地語系化字串。
        /// </summary>
        internal static string ReceivedString {
            get {
                return ResourceManager.GetString("ReceivedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Receive 的當地語系化字串。
        /// </summary>
        internal static string ReceiveString {
            get {
                return ResourceManager.GetString("ReceiveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Referrals 的當地語系化字串。
        /// </summary>
        internal static string ReferralsString {
            get {
                return ResourceManager.GetString("ReferralsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Remark 的當地語系化字串。
        /// </summary>
        internal static string RemarkString {
            get {
                return ResourceManager.GetString("RemarkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Result 的當地語系化字串。
        /// </summary>
        internal static string ResultString {
            get {
                return ResourceManager.GetString("ResultString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sales Mgt 的當地語系化字串。
        /// </summary>
        internal static string SalesMgtString {
            get {
                return ResourceManager.GetString("SalesMgtString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Schedule 的當地語系化字串。
        /// </summary>
        internal static string ScheduleString {
            get {
                return ResourceManager.GetString("ScheduleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Search Mgt 的當地語系化字串。
        /// </summary>
        internal static string SearchMgtString {
            get {
                return ResourceManager.GetString("SearchMgtString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Result 的當地語系化字串。
        /// </summary>
        internal static string SearchResultString {
            get {
                return ResourceManager.GetString("SearchResultString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Search 的當地語系化字串。
        /// </summary>
        internal static string SearchString {
            get {
                return ResourceManager.GetString("SearchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select any store 的當地語系化字串。
        /// </summary>
        internal static string SelectStoreString {
            get {
                return ResourceManager.GetString("SelectStoreString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select an item 的當地語系化字串。
        /// </summary>
        internal static string SeletionRemindString {
            get {
                return ResourceManager.GetString("SeletionRemindString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Simplified Chinese 的當地語系化字串。
        /// </summary>
        internal static string SimplifiedChineseString {
            get {
                return ResourceManager.GetString("SimplifiedChineseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please input SN 的當地語系化字串。
        /// </summary>
        internal static string SnInputString {
            get {
                return ResourceManager.GetString("SnInputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SNS 的當地語系化字串。
        /// </summary>
        internal static string SNSMgtString {
            get {
                return ResourceManager.GetString("SNSMgtString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SN 的當地語系化字串。
        /// </summary>
        internal static string SnString {
            get {
                return ResourceManager.GetString("SnString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Status 的當地語系化字串。
        /// </summary>
        internal static string StatusString {
            get {
                return ResourceManager.GetString("StatusString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Store Mgt 的當地語系化字串。
        /// </summary>
        internal static string StoreMgtString {
            get {
                return ResourceManager.GetString("StoreMgtString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please input a store name 的當地語系化字串。
        /// </summary>
        internal static string StoreNameInputString {
            get {
                return ResourceManager.GetString("StoreNameInputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Store SN 的當地語系化字串。
        /// </summary>
        internal static string StoreSnString {
            get {
                return ResourceManager.GetString("StoreSnString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Store Name 的當地語系化字串。
        /// </summary>
        internal static string StoreString {
            get {
                return ResourceManager.GetString("StoreString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Style 的當地語系化字串。
        /// </summary>
        internal static string StyleMaintainString {
            get {
                return ResourceManager.GetString("StyleMaintainString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System Mgt 的當地語系化字串。
        /// </summary>
        internal static string SysMgtString {
            get {
                return ResourceManager.GetString("SysMgtString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Timetable 的當地語系化字串。
        /// </summary>
        internal static string TimetableMaintainString {
            get {
                return ResourceManager.GetString("TimetableMaintainString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Traditional Chinese 的當地語系化字串。
        /// </summary>
        internal static string TraditionalChineseString {
            get {
                return ResourceManager.GetString("TraditionalChineseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Input the unit 的當地語系化字串。
        /// </summary>
        internal static string UnitInputString {
            get {
                return ResourceManager.GetString("UnitInputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unit 的當地語系化字串。
        /// </summary>
        internal static string UnitString {
            get {
                return ResourceManager.GetString("UnitString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update 的當地語系化字串。
        /// </summary>
        internal static string UpdateString {
            get {
                return ResourceManager.GetString("UpdateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update time 的當地語系化字串。
        /// </summary>
        internal static string UpdateTimeString {
            get {
                return ResourceManager.GetString("UpdateTimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Upload 的當地語系化字串。
        /// </summary>
        internal static string UploadString {
            get {
                return ResourceManager.GetString("UploadString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 View 的當地語系化字串。
        /// </summary>
        internal static string ViewString {
            get {
                return ResourceManager.GetString("ViewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Wedding Item 的當地語系化字串。
        /// </summary>
        internal static string WeddingItemMaintainString {
            get {
                return ResourceManager.GetString("WeddingItemMaintainString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Work Reminder 的當地語系化字串。
        /// </summary>
        internal static string WorkReminderString {
            get {
                return ResourceManager.GetString("WorkReminderString", resourceCulture);
            }
        }
    }
}
